# Generated by Django 5.2.17 on 2026-09-25 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Accessories', 'Accessories')], max_length=50)),
                ('asset_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Needs attention', 'Needs attention')], default='Available', max_length=40)),
                ('location', models.CharField(default='Floor 2 - Dev Team', max_length=160)),
                ('image', models.CharField(default='🖥️', max_length=20)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=160)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('warranty_till', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_id'],
            },
        ),
        migrations.CreateModel(
            name='FloorZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
